import React, { useState } from 'react';
import { AlertTriangle, ShieldAlert, CheckCircle2, Clock, MapPin, Radio, Lock } from 'lucide-react';

export default function SecurityAlertsTab({ alerts, onResolveAlert }) {
  const [resolvingId, setResolvingId] = useState(null);
  const [resolutionNotes, setResolutionNotes] = useState('');

  const unresolved = alerts.filter(a => !a.resolved);
  const resolved = alerts.filter(a => a.resolved);

  const handleConfirmResolve = (alertId) => {
    onResolveAlert(alertId, resolutionNotes || 'Resolved by security admin');
    setResolvingId(null);
    setResolutionNotes('');
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
      <div>
        <h2 style={{ fontSize: '1.4rem', fontWeight: 800, color: '#ffffff' }}>
          Security Incident & Intrusion Center
        </h2>
        <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', marginTop: '0.2rem' }}>
          Real-time security warnings generated by physical ESP32 buzzer triggers & unauthorized RFID scans.
        </p>
      </div>

      {/* Active Unresolved Alerts Section */}
      <div>
        <h3 style={{ fontSize: '1.1rem', fontWeight: 700, color: '#fb7185', marginBottom: '1rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
          <AlertTriangle size={20} /> Active Unresolved Security Incidents ({unresolved.length})
        </h3>

        {unresolved.length === 0 ? (
          <div className="glass-panel" style={{ padding: '2rem', textAlign: 'center', color: 'var(--text-muted)' }}>
            <CheckCircle2 size={36} color="#10b981" style={{ margin: '0 auto 0.5rem auto' }} />
            <div style={{ fontWeight: 700, color: '#ffffff' }}>No Active Security Violations</div>
            <p style={{ fontSize: '0.8rem', marginTop: '0.2rem' }}>All locker access attempts are currently verified and authorized.</p>
          </div>
        ) : (
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: '1rem' }}>
            {unresolved.map((alert) => (
              <div 
                key={alert.alert_id}
                className="alert-banner-flashing"
                style={{
                  padding: '1.25rem',
                  borderRadius: 'var(--radius-md)',
                  display: 'flex',
                  flexDirection: 'column',
                  gap: '0.75rem'
                }}
              >
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                  <span style={{ fontWeight: 800, color: '#ffffff', fontSize: '1.05rem', display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
                    <ShieldAlert size={18} color="#f43f5e" /> {alert.alert_type}
                  </span>
                  <span style={{
                    background: '#f43f5e',
                    color: '#ffffff',
                    fontSize: '0.65rem',
                    fontWeight: 800,
                    padding: '0.15rem 0.5rem',
                    borderRadius: '4px'
                  }}>
                    HIGH SEVERITY
                  </span>
                </div>

                <div style={{ fontSize: '0.85rem', color: '#fca5a5', lineHeight: 1.4 }}>
                  {alert.notes || `Unauthorized RFID scan detected on Locker ${alert.locker_id}`}
                </div>

                <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.75rem', color: 'var(--text-secondary)' }}>
                  <span>Locker: <strong style={{ color: '#ffffff' }}>{alert.locker_id}</strong></span>
                  <span>RFID: <strong style={{ color: '#ffffff', fontFamily: 'var(--font-mono)' }}>{alert.rfid_uid || 'UNKNOWN'}</strong></span>
                </div>

                <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', display: 'flex', alignItems: 'center', gap: '0.3rem' }}>
                  <Clock size={12} /> Detected: {alert.timestamp}
                </div>

                {resolvingId === alert.alert_id ? (
                  <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem', marginTop: '0.5rem' }}>
                    <input 
                      type="text"
                      placeholder="Resolution notes (e.g. Verified student ID)..."
                      value={resolutionNotes}
                      onChange={(e) => setResolutionNotes(e.target.value)}
                      style={{
                        background: 'rgba(15, 23, 42, 0.9)',
                        border: '1px solid rgba(255,255,255,0.2)',
                        borderRadius: 'var(--radius-sm)',
                        padding: '0.5rem',
                        color: '#ffffff',
                        fontSize: '0.8rem',
                        outline: 'none'
                      }}
                    />
                    <div style={{ display: 'flex', gap: '0.5rem' }}>
                      <button onClick={() => handleConfirmResolve(alert.alert_id)} className="btn-primary" style={{ flex: 1, padding: '0.4rem', fontSize: '0.75rem' }}>
                        Mark Resolved
                      </button>
                      <button onClick={() => setResolvingId(null)} className="btn-secondary" style={{ padding: '0.4rem', fontSize: '0.75rem' }}>
                        Cancel
                      </button>
                    </div>
                  </div>
                ) : (
                  <button 
                    onClick={() => setResolvingId(alert.alert_id)}
                    className="btn-secondary" 
                    style={{ marginTop: '0.25rem', padding: '0.45rem', fontSize: '0.8rem', justifyContent: 'center' }}
                  >
                    Acknowledge & Resolve Alert
                  </button>
                )}

              </div>
            ))}
          </div>
        )}
      </div>

      {/* Resolved Alerts History */}
      <div>
        <h3 style={{ fontSize: '1.1rem', fontWeight: 700, color: 'var(--text-secondary)', marginBottom: '1rem' }}>
          Resolved Alert History
        </h3>

        <div className="glass-panel" style={{ overflowX: 'auto' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left', fontSize: '0.85rem' }}>
            <thead>
              <tr style={{ borderBottom: '1px solid var(--border-color)', color: 'var(--text-muted)' }}>
                <th style={{ padding: '1rem' }}>Alert ID</th>
                <th style={{ padding: '1rem' }}>Alert Type</th>
                <th style={{ padding: '1rem' }}>Locker</th>
                <th style={{ padding: '1rem' }}>RFID Tag</th>
                <th style={{ padding: '1rem' }}>Timestamp</th>
                <th style={{ padding: '1rem' }}>Status</th>
              </tr>
            </thead>
            <tbody>
              {resolved.map((a) => (
                <tr key={a.alert_id} style={{ borderBottom: '1px solid rgba(255,255,255,0.05)' }}>
                  <td style={{ padding: '1rem', fontWeight: 700 }}>{a.alert_id}</td>
                  <td style={{ padding: '1rem' }}>{a.alert_type}</td>
                  <td style={{ padding: '1rem' }}>{a.locker_id}</td>
                  <td style={{ padding: '1rem', fontFamily: 'var(--font-mono)' }}>{a.rfid_uid}</td>
                  <td style={{ padding: '1rem', color: 'var(--text-muted)', fontSize: '0.75rem' }}>{a.timestamp}</td>
                  <td style={{ padding: '1rem' }}>
                    <span className="badge badge-granted">RESOLVED</span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

    </div>
  );
}
